### PR TITLE
revise convertToShortString

### PR DESCRIPTION
**Pull request by jakob-r**
In order so solve Issue #69

### CODE REVIEW

**Comment by berndbischl** [comment]
- news is wrong. you are creating version 1.11. pls really watch out fot stuff like that

- can you 10 min try to add a few more tests. i am getting a bit worried what this will affect

otherwise: thx

**Comment by berndbischl** [comment]
well more:

you changed apparently the behavior, but not the docs....
that can never be correct, right? pls adapt docs

**Comment by jakob-r** [comment]
Is it better now? I was not exactly sure what behaviour changes i made (except the expression printeing). I also doubt that the a changed output will break anything. At most a test that expects some output. Bus obviously we never really used the function externally in the first place.

**Comment by berndbischl** [comment]
i guess we can merge. thx

**Pull request merged**
