### PR TITLE
Suggest: namedLapply

### PR DESCRIPTION
**Pull request by jakob-r**
maybe you find it not so usefull but i find myself using somehting like this often when you need the name to access other items and want to have a named list at the end.

### CODE REVIEW

**Comment by berndbischl** [comment]
I have no problem having maybe more "exotic" functions in here, if people need them.
But if we use them more often we should be kinda sure about the API.

Just so I understand what you really wanna do:
You want to map over xs (the list) and names of xs, with a function f(x, name)?
I think that came up as a use case for myself a couple of times.

@mllg 
Opinion?

**Comment by berndbischl** [comment]
Also: Wouldnt it in the code be better (and faster?) then to explicitly call Map / mapply?

**Comment by mllg** [comment]
I do not see any advantage over
```{r}
Map(function(name, x) ..., name = names(x), x = x)
```
which is easy to read and clear.

**Comment by berndbischl** [comment]
Ok, closing for now the. Please reopen, if the discussion should be continued. 
And I guess it saves time to discuss these things before the code in created for a PR.

**Comment by jakob-r** [comment]
Oh - i wasn't aware that `Map` also names the result accordingly. Great.

**Pull request closed without merging**
