### PR TITLE
New function printHead

### PR DESCRIPTION
**Pull request by jakobbossek**
... as introduced in mlr recently. However, this is a generalized version which works for data.frame/matrix/vector/list objects.

The function behaves like `print(head(x, n))` with the addition, that some info on the number of rows/elements is printed if there are more than n rows/elements in the object.

### CODE REVIEW

**Comment by berndbischl** [comment]
i have added a little doc fix. 

but your functions works on lists, and other stuff too. you have not documented this, the docs only say matrix and df.

**Comment by jakobbossek** [comment]
Oh I see. Is the following OK? Looks kind of bloated.
```
#' @param x [\code{data.frame} | \code{matrix} | \code{list} | \code{vector}]\cr
#'   Data frame, matrix, list or vector.
```

**Comment by berndbischl** [comment]
better bloated than incorrect. IMHO ok

**Comment by berndbischl** [comment]
also you seem to have a tendency to "repeat" the data types in the arg explanation in the 2nd line.
i am not going to force you to remove this, but this really is unnecessary bloat :)

**Comment by jakobbossek** [comment]
Yeah, should be correct. Just asked myself if you have a nicer/shorter solution.
So simply replace the second line with `Object.`?

**Comment by berndbischl** [comment]
> Just asked myself if you have a nicer/shorter solution.

well, lists are also vectors in R, but i would not use that to shorten the docs. so i dont have a better solution.

> So simply replace the second line with Object.?

for example.

 i made the comment because i saw that a couple of times now in your PRs and also PRs by many other people. i think they do it because usually nobody uses this formal-bracket thing we do. so you have to mention the type "manually"

**Comment by jakobbossek** [comment]
Ok. You are right. Going to may more attention to this in the future 👍

**Comment by jakobbossek** [comment]
I think this is ready to merge now.

**Pull request merged**
